name: flutter_socket_chat_app
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  dash_chat: ^1.0.8
  shared_preferences: ^0.5.4+3
  http: ^0.12.0+2
  toast: ^0.1.5
  equatable: ^0.1.6
  flutter_socket_io: ^0.6.0
  socket_io_client: ^0.9.5
  bloc: ^0.13.0
  flutter_bloc: ^0.13.0
  flutter_dotenv: ^2.0.3
  firebase_ml_vision: ^0.2.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - .env
